project:
  type: website
  output-dir: _site
  resources: _include
  render:
    - "*.qmd"
    - "!rdm_when.md"

website:
  title: "Data Curation at Royce Presentations"
  favicon: "_include/favicon.png"
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Open Research Talks"
        menu:
        - href: 2024-07-01_open_research_in_practice_actionable_materials.qmd
          text: "Why Open Research?"
      - text: "RDM Tool Talks"
        menu:
          - href: 2023-07-12_why_git.qmd
            text: "Why use Git?"
          - href: 2023-07-12_how_to_rdmp.qmd
            text: "RDM Planning"
          - href: 2024-07-26_general_intro_to_ampletracks.qmd
            text: "Ampletracks"

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true
    execute:
      freeze: auto
  revealjs:
      html-q-tags: true
      theme: [_include/styles/custom.scss, default]
      incremental: true
      execute:
        eval: false
        message: false
        warning: false
        echo: false
      code:
        code-overflow: wrap
      resources: [_include/*, "_include/HenryRoyceInstitute_MasterLogo_RGB_Grey (MAIN).png", "_include/royce_banner.svg", "_include/RoyceBorder.svg",site_libs/*]
      # embed-resources: true
      resource-path: 
        - _include
      include-in-header: 
        file: sources.html