on:
  push:
    branches:
      - main

name: Render and Publish
permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if branch exists 
        id: check_branch_exists
        continue-on-error: true
        run: |
          git fetch
          git branch -a
          git branch -a | grep gh-pages
          # git branch -a | grep gh-pages >> "$GITHUB_OUTPUT"

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Echo outcome
        run: |
          echo ${{ steps.check_branch_exists.outcome }}

      - name: Create gh-pages if not exists
        env:
          branch_name: gh-pages
        if: ${{ steps.check_branch_exists.outcome != 'success'}}    
        run: | 
          git checkout -b $branch_name
          git rm -rf .
          git commit --allow-empty -m "Initial commit on orphan branch"
          git push -u origin $branch_name
          git fetch
          git pull
          git checkout main

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
          # To install LaTeX to build PDF book 
          # tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      # - name: Render Quarto Project
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     to: html # If set, it will be equivalent to `quarto render --to html`
      #     path: .

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
      - name: Create dir files
        run: |
          git checkout gh-pages
          cp -vr _include $target_dir
          git add *
          git commit -m 'move theme files to directory'
          git push -u origin gh-pages
        env:
          target_dir: site_libs/revealjs/dist/theme